'\" t
.ig
Copyright 2013 Waitman Gobble

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
   
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
..
.
.
.TH prhistory 7 "27 January 2013" "prhistory version 1.0"
.
.
.
.SH NAME
.
.B prhistory
.
.SH SYNOPSIS
.

cd /usr/ports/lang/perl5.16

prhistory


prhistory perl


prhistory -p 123456
.
.SH DESCRIPTION

This program searches the GNATS database for PR corresponding to a port. The user can get a list of PR for the port by changing to the path of the port and typing prhistory, or they may type prhistory <portname>

.
.SH OPTIONS
.IP -h
I will show HELP
.IP -l
I will show legend
.IP -u
We will update PR db from the WWW
.IP -c
You will see closed PR TOO (AS WELL) if AVAILABLE
.IP -p
Display PR (ports only).

.SH FILES

prhistory stores the PR database in /var/db/ports/ports-pr.db. This file is an SQLite3 database.

.
.
.SH AUTHOR
.
Manual page by Waitman Gobble
